use_frameworks!

platform :ios, '8.0'

target 'YDLHModuleSDK_Example' do
  pod 'YDLHModuleSDK', :path => '../'

  target 'YDLHModuleSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
  
  pod 'YDBaseClassSDK' ,:git =>"https://github.com/JamWangJam/YDBaseClassSDK.git"
  pod 'YDCategorySDK' ,:git =>"https://github.com/JamWangJam/YDCategorySDK.git"
  pod 'YDCTMediatorSDK' ,:git =>"https://github.com/JamWangJam/YDCTMediatorSDK.git"
  
end
