use_frameworks!

platform :ios, '8.0'

target 'YDLHModuleSDK_Example' do
  pod 'YDLHModuleSDK', :path => '../'

  target 'YDLHModuleSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
